### ISSUE TITLE
AMQ Custom song list game script: "answer results" listener failed error

### ISSUE THREAD

**Issue by Otakudweeb** [kempanator/amq-scripts#1]
https://gyazo.com/f0340c4f99e7f209dc32ed491013d0b0

Plays the first song according to the list just fine, but then stalls during answer reveal and with no reveal and displays CSL Error: "answer results" listener failed. Persists after multiple computer/browser restarts and re-installations.

**Comment by kempanator** [comment]
delete AMQ Song List script by joseph

**Comment by Otakudweeb** [comment]
that worked! thanks for the immediate response too, really appreciate it!
